"use strict";
const KEY="projectx_ultra_v2";
const blank={view:"home",activeProjectId:null,tab:"overview",plan:"Free",credits:20,model:"Auto",mode:"Build",sidebar:false,reduceMotion:false,compact:false,projects:[],chat:[],attachments:[],activity:[]};
const templates=[
 {icon:"⌁",title:"Launch a local service",type:"Local service",prompt:"I want to start a local service and get my first 20 paying customers.",desc:"Offer, pricing, customer intake, booking, operations and acquisition."},
 {icon:"◫",title:"Build a SaaS",type:"Software",prompt:"I want to build a SaaS product around a problem I know well.",desc:"Product, auth, data, billing, onboarding, analytics and growth."},
 {icon:"◉",title:"Launch a creator brand",type:"Creator",prompt:"I want to build a creator brand and grow a real audience.",desc:"Positioning, content system, publishing workflow and monetization."},
 {icon:"◇",title:"Build a game",type:"Game",prompt:"I want to build a game people will actually keep playing.",desc:"Core loop, progression, economy, analytics and launch."},
 {icon:"□",title:"Launch an online store",type:"Commerce",prompt:"I want to launch an online store for a product I can source or make.",desc:"Catalog, storefront, checkout, fulfillment and retention."},
 {icon:"↔",title:"Build a marketplace",type:"Marketplace",prompt:"I want to build a marketplace that connects buyers and sellers.",desc:"Listings, matching, trust, payments and marketplace growth."}
];
let state=merge(blank,load());
function merge(a,b){return {...a,...b}}
function load(){try{return JSON.parse(localStorage.getItem(KEY)||"{}")||{}}catch{return {}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function money(n){return "₹"+Number(n||0).toLocaleString("en-IN")}
function id(){return "p_"+Math.random().toString(36).slice(2,10)}
function p(){return state.projects.find(x=>x.id===state.activeProjectId)||null}
function setView(v){state.view=v;save();render()}
function toast(t){const r=document.getElementById("toastRoot");const e=document.createElement("div");e.className="toast";e.textContent=t;r.appendChild(e);setTimeout(()=>e.remove(),2600)}
function render(){document.body.classList.toggle("reduced-motion",state.reduceMotion);document.getElementById("app").innerHTML=layout()}
function layout(){return `<div class="app"><aside class="sidebar ${state.sidebar?'open':''}">${sidebar()}</aside><main class="main"><header class="topbar"><div class="crumbs"><button class="mobile-menu" onclick="toggleSide()">☰</button><span class="dim">Workspace</span><span class="slash">/</span><strong>${esc(title(state.view))}</strong>${p()?`<span class="slash">/</span><span>${esc(p().name)}</span>`:""}</div><div class="top-actions"><button class="search-btn" onclick="openCommand()"><span>⌕ Search anything</span><kbd>Ctrl K</kbd></button><button class="icon-btn" onclick="openUpgrade()">↗</button><div class="avatar">PX</div></div></header><div class="page">${page()}</div></main></div>`}
function title(v){return ({home:"Home",explore:"Explore",projects:"Projects",build:"Build",assets:"Assets",data:"Data",automate:"Automations",analytics:"Analytics",ai:"AI Co-Founder",settings:"Settings"}[v]||"Home")}
function sidebar(){const nav=[["home","⌂","Home"],["explore","✦","Explore"],["projects","▦","Projects"],["build","＋","Build"]],tools=[["assets","◇","Assets"],["data","◫","Data"],["automate","↯","Automations"],["analytics","◒","Analytics"],["ai","◎","AI Co-Founder"]];return `<button class="brand" onclick="setView('home')"><span class="brand-mark">✦</span><span>PROJECT X</span></button><button class="workspace-switch" onclick="openWorkspaceMenu()"><span class="ws-dot"></span><div style="flex:1"><strong>Founder workspace</strong><span>${esc(state.plan)} · ${state.credits} AI credits</span></div><span>⌄</span></button><nav class="nav">${nav.map(n=>navBtn(n)).join("")}<div class="nav-section">Workspace</div>${tools.map(n=>navBtn(n)).join("")}</nav><div class="side-spacer"></div><div class="side-foot"><button class="nav-btn" onclick="setView('settings')"><span class="nav-icon">⚙</span>Settings</button><button class="upgrade-mini" onclick="openUpgrade()"><strong>Upgrade</strong><span>Unlock advanced building, agents and higher limits →</span></button><div class="profile"><div class="avatar">PX</div><div><strong>Founder</strong><span>Local prototype</span></div></div></div>`}
function navBtn(n){return `<button class="nav-btn ${state.view===n[0]?'active':''}" onclick="setView('${n[0]}')"><span class="nav-icon">${n[1]}</span>${n[2]}</button>`}
function page(){switch(state.view){case"home":return home();case"explore":return explore();case"projects":return projectsPage();case"build":return p()?workspace():buildLanding();case"assets":return globalAssets();case"data":return p()?projectData():selectProject();case"automate":return p()?projectAutomations():selectProject();case"analytics":return p()?projectAnalytics():selectProject();case"ai":return p()?fullAI():selectProject();case"settings":return settings();default:return home()}}
function home(){return `<div class="max"><section class="hero"><div class="eyebrow">AI creation + execution OS</div><h1>What do you want<br/><span>to make happen?</span></h1><p class="hero-copy">Describe the goal. The AI decides what needs to exist, builds it, creates the assets, gives you the exact setup steps, and keeps the project moving.</p>${composer("home")}${state.projects.length?`<div class="home-grid"><div class="panel"><div class="panel-head"><div><div class="eyebrow">Recent projects</div><h2>Keep building</h2></div><button class="ghost-btn" onclick="setView('projects')">View all →</button></div><div class="project-list">${state.projects.slice(0,4).map(homeProject).join("")}</div></div><div class="panel"><div class="eyebrow">Your workspace</div><h2 style="margin:5px 0 0;font-size:15px">At a glance</h2><div class="metric-grid"><div class="metric"><span>Projects</span><strong>${state.projects.length}</strong><small>Active ambitions</small></div><div class="metric"><span>AI credits</span><strong>${state.credits}</strong><small>${state.plan} plan</small></div><div class="metric"><span>Assets</span><strong>${state.projects.reduce((n,x)=>n+(x.assets?.length||0),0)}</strong><small>Generated outputs</small></div><div class="metric"><span>Ready states</span><strong>${state.projects.filter(x=>x.progress>=85).length}</strong><small>Close to launch</small></div></div></div></div>`:`<div class="suggestions">${["Launch a local service","Build a SaaS","Create a creator brand","Build a game"].map(x=>`<button class="suggestion" onclick="startPrompt('${esc(x)}')">${esc(x)}</button>`).join("")}</div>`}</section></div>`}
function homeProject(x){return `<button class="project-item" onclick="openProject('${x.id}')"><div class="project-item-top"><span class="mini">${esc(x.type)}</span><span class="status ${x.progress>=70?'ready':''}">${x.progress>=85?'Ready soon':x.progress+'%'}</span></div><h3>${esc(x.name)}</h3><p>${esc(x.goal)}</p><div class="progress"><span style="width:${Math.min(100,x.progress)}%"></span></div></button>`}
function composer(kind){return `<div class="composer" id="composer"><div class="composer-main"><textarea id="${kind}Prompt" placeholder="Tell the AI what you want to build, launch, fix, automate or achieve…"></textarea>${state.attachments.length?`<div class="chips">${state.attachments.map((f,i)=>`<div class="file-chip">${f.kind==='image'?'🖼️':'📄'} ${esc(f.name)} <button onclick="removeAttachment(${i})">×</button></div>`).join("")}</div>`:""}</div><div class="composer-tools"><div class="tool-left"><button class="tool-btn" onclick="openAttachment()">📎 Attach</button><button class="tool-btn" onclick="openContextMenu()">＋ Context</button><div class="selector"><button class="tool-btn" onclick="toggleSelector('modeMenu')">${state.mode} ▾</button><div id="modeMenu" class="selector-menu hidden">${["Discuss","Plan","Build","Analyze","Fix","Research","Execute"].map(m=>`<button onclick="setComposerMode('${m}')"><strong>${m}</strong><span>${modeDesc(m)}</span></button>`).join("")}</div></div><div class="selector"><button class="tool-btn" onclick="toggleSelector('modelMenu')">✦ ${state.model} ▾</button><div id="modelMenu" class="selector-menu hidden">${modelOptions().map(m=>`<button onclick="setModel('${m.n}')"><strong>${m.n}</strong><span>${m.d}</span></button>`).join("")}</div></div></div><div class="tool-right"><button class="tool-btn" onclick="openAISettings()">⚙</button><button class="primary-btn" onclick="startPrompt(document.getElementById('${kind}Prompt').value)">${state.mode==='Discuss'?'Discuss':'Build it'} ↑</button></div></div></div>`}
function modeDesc(m){return ({Discuss:"Think without changing the project",Plan:"Design or revise the project blueprint",Build:"Make changes to the project",Analyze:"Inspect data, metrics and context",Fix:"Find and repair problems",Research:"Gather useful external context",Execute:"Run approved actions"}[m])}
function modelOptions(){return[{n:"Auto",d:"Choose the best route automatically"},{n:"Fast",d:"Lower latency for simple tasks"},{n:"Reasoning",d:"Deeper analysis for complex decisions"},{n:"Builder",d:"Optimized for building software"},{n:"Premium",d:"Highest-quality generation"}]}
function explore(){return `<div class="max"><div class="eyebrow">Explore</div><h1 class="page-title">Start with an outcome.</h1><p class="page-sub">Outcome templates are starting points. The AI reshapes the whole system around your budget, skills, time and context.</p><div class="explore-grid">${templates.map((t,i)=>`<button class="template-card" onclick="useTemplate(${i})"><div class="template-icon">${t.icon}</div><h3>${esc(t.title)}</h3><p>${esc(t.desc)}</p><span class="template-arrow">Build this →</span></button>`).join("")}</div><div class="panel" style="margin-top:12px"><div class="eyebrow">Different by design</div><h2 style="font-size:20px;margin:6px 0">The user asks for an outcome. The AI figures out the system.</h2><p class="muted">A business, SaaS, game, creator operation, product or service can all share the same creation engine.</p></div></div>`}
function projectsPage(){return `<div class="max"><div class="panel-head"><div><div class="eyebrow">Workspace</div><h1 class="page-title">Projects</h1><p class="page-sub">Every ambition becomes a persistent project you can build, operate and improve.</p></div><button class="primary-btn" onclick="setView('build')">＋ New project</button></div>${state.projects.length?`<div class="explore-grid">${state.projects.map(x=>`<button class="template-card" onclick="openProject('${x.id}')"><div class="template-icon">${x.progress>=85?'✓':'✦'}</div><h3>${esc(x.name)}</h3><p>${esc(x.goal)}</p><div style="margin-top:auto"><div class="progress"><span style="width:${x.progress}%"></span></div><div style="display:flex;justify-content:space-between;margin-top:7px"><span class="mini">${esc(x.type)}</span><span class="mini">${x.progress}%</span></div></div></button>`).join("")}</div>`:`<div class="panel" style="margin-top:20px;text-align:center;padding:50px"><h2 style="margin:0;font-size:18px">No projects yet.</h2><p class="muted">Start with an ambition from Home.</p></div>`}</div>`}
function buildLanding(){return `<div class="max"><div class="hero" style="margin-top:3vh"><div class="eyebrow">Build</div><h1 style="font-size:46px">Create the thing you actually need.</h1><p class="hero-copy">Use the full builder experience without needing to understand software architecture first.</p>${composer("build")}</div></div>`}
function workspace(){const x=p();return `<div class="workspace max"><div class="workspace-toolbar"><div><div class="eyebrow">${esc(x.type)} project</div><h1 class="page-title" style="font-size:25px">${esc(x.name)}</h1><p class="page-sub">${esc(x.goal)}</p></div><div class="toolbar-actions"><button class="secondary-btn" onclick="openVersionModal()">↺ Versions</button><button class="secondary-btn" onclick="openLaunchModal()">◎ Ready & Launch</button><button class="primary-btn" onclick="simulateBuild()">✦ Build missing</button></div></div><div class="workspace-grid"><nav class="project-nav">${["overview","blueprint","build","tasks","assets","data","automate","analytics","ai","versions"].map(t=>`<button class="ws-link ${state.tab===t?'active':''}" onclick="setTab('${t}')"><span>${tabIcon(t)}</span>${capitalize(t)}</button>`).join("")}</nav><section class="builder-wrap">${projectTab(x)}</section><aside class="builder-side">${miniAI(x)}</aside></div></div>`}
function tabIcon(t){return ({overview:"◈",blueprint:"⌬",build:"✦",tasks:"✓",assets:"◇",data:"◫",automate:"↯",analytics:"◒",ai:"◎",versions:"↺"}[t])}
function capitalize(s){return s[0].toUpperCase()+s.slice(1)}
function setTab(t){state.tab=t;save();render()}
function projectTab(x){switch(state.tab){case"overview":return overview(x);case"blueprint":return blueprint(x);case"build":return builder(x);case"tasks":return tasks(x);case"assets":return assets(x);case"data":return projectData(x);case"automate":return projectAutomations(x);case"analytics":return projectAnalytics(x);case"ai":return fullAI(x);case"versions":return versions(x);default:return overview(x)}}
function overview(x){return `<div class="tabs-page"><div class="grid-3"><div class="metric"><span>Progress</span><strong>${x.progress}%</strong><small>${x.progress>=85?'Ready soon':'In build'}</small></div><div class="metric"><span>Goal</span><strong>${x.targetCount||20}</strong><small>Primary outcome units</small></div><div class="metric"><span>AI credits</span><strong>${state.credits}</strong><small>${state.model} model</small></div></div><div class="panel"><div class="panel-head"><div><div class="eyebrow">Next best action</div><h2 style="font-size:18px;margin:5px 0">${esc(x.nextAction||'Validate the core outcome with five real people.')}</h2><p class="muted">The AI keeps one concrete step in front of you instead of making you manage a giant checklist.</p></div><button class="primary-btn" onclick="executeNext()">Do this →</button></div></div><div class="grid-2"><div class="panel"><div class="eyebrow">Goal path</div><h3 style="font-size:15px;margin:5px 0 10px">${x.progress>=85?'Ready state approaching':'Execution path'}</h3>${x.milestones.map(m=>`<div class="setting"><div><strong>${esc(m.name)}</strong><p>${esc(m.detail)}</p></div><span class="badge ${m.done?'good':''}">${m.done?'Done':'Next'}</span></div>`).join("")}</div><div class="panel"><div class="eyebrow">AI insight</div><h3 style="font-size:15px;margin:5px 0 8px">${esc(x.insight||'Build the smallest useful version first, then use real outcomes to guide the next iteration.')}</h3><p class="muted">This is the project memory surface: decisions, outcomes and context stay attached to the project.</p></div></div></div>`}
function blueprint(x){return `<div class="tabs-page"><div class="dash-head"><div><div class="eyebrow">Living blueprint</div><h2 style="font-size:19px;margin:5px 0">Everything the ambition needs.</h2><p class="muted">Systems can change as reality changes.</p></div><button class="primary-btn" onclick="simulateBuild()">✦ Build missing pieces</button></div><div class="grid-2">${x.systems.map(s=>`<div class="system"><div style="display:flex;justify-content:space-between;align-items:center"><div class="asset-icon">${s.icon}</div><span class="badge ${s.status==='ready'?'good':''}">${s.status==='ready'?'Ready':'In progress'}</span></div><h3>${esc(s.name)}</h3><p>${esc(s.summary)}</p><ul>${s.items.map(i=>`<li><span class="check">✓</span>${esc(i)}</li>`).join("")}</ul></div>`).join("")}</div></div>`}
function builder(x){return `<div class="canvas-card"><div class="canvas-head"><div class="device-tabs"><button class="active">Desktop</button><button>Tablet</button><button>Mobile</button></div><span class="mini">Live preview · auto-saved</span></div><div class="canvas-stage"><div class="browser"><div class="browser-top"><i></i><i></i><i></i><label>${esc((x.name||'project').toLowerCase().replace(/\s+/g,'-'))}.preview</label></div><div class="fake-site"><div class="fake-nav"><strong>${esc((x.name.split(' ')[0]||'PROJECT').toUpperCase())}</strong><span>Home　Services　About　 <b>Get started</b></span></div><div class="fake-hero"><div class="kicker">AI-GENERATED EXPERIENCE</div><h2>Build the system.<br/><em>Ship the outcome.</em></h2><p>${esc(x.prompt||'A working product generated from your project context.')}</p><div class="fake-cta"><button>Get started →</button><span>Explore the flow</span></div></div><div class="fake-cards"><div></div><div></div><div></div></div></div></div></div></div></div>`}
function miniAI(x){return `<div class="side-tabs"><button class="active">AI Co-Founder</button><button onclick="setTab('versions')">Activity</button></div><div class="chat" id="miniChat">${state.chat.slice(-7).map(msg=>chatMsg(msg)).join("")}</div><div class="quick-chips"><button class="quick-chip" onclick="fillChat('What should I do next?')">Next action</button><button class="quick-chip" onclick="fillChat('Analyze the project.')">Analyze</button><button class="quick-chip" onclick="fillChat('Build the missing pieces.')">Build</button></div><div class="chat-compose"><textarea id="miniInput" placeholder="Ask the co-founder…"></textarea><div class="chat-bottom"><div class="mode-row">${["Discuss","Plan","Build"].map(m=>`<button class="mode ${state.mode===m?'active':''}" onclick="setMode('${m}')">${m}</button>`).join("")}</div><button class="run-btn" onclick="sendChat('miniInput')">Send ↑</button></div></div>`}
function chatMsg(m){return `<div class="chat-msg ${m.role}"><div class="chat-avatar">${m.role==='ai'?'✦':'PX'}</div><div><strong>${m.role==='ai'?'AI':'You'}</strong><p>${esc(m.text)}</p></div></div>`}
function tasks(x){return `<div class="tabs-page"><div class="dash-head"><div><div class="eyebrow">Execution</div><h2 style="font-size:19px;margin:5px 0">Tasks that move the project.</h2></div><button class="secondary-btn" onclick="addTask()">＋ Add task</button></div><div class="task-list">${x.tasks.map((t,i)=>`<div class="task ${t.done?'done':''}"><button class="task-check" onclick="toggleTask(${i})">${t.done?'✓':''}</button><div class="task-main"><strong>${esc(t.text)}</strong><span>${esc(t.tag)} · ${esc(t.priority)}</span></div><button class="icon-btn" onclick="toast('Task actions coming soon')">⋯</button></div>`).join("")}</div></div>`}
function assets(x){return `<div class="tabs-page"><div class="dash-head"><div><div class="eyebrow">Asset library</div><h2 style="font-size:19px;margin:5px 0">Usable things your AI has made.</h2><p class="muted">Documents, forms, pages, scripts and other outputs stay linked to the project.</p></div><button class="primary-btn" onclick="generateAsset()">＋ Generate asset</button></div><div class="asset-list">${x.assets.map((a,i)=>`<button class="asset" onclick="previewAsset(${i})"><div style="display:flex;gap:9px;align-items:center"><div class="asset-icon">${a.type==='Website'?'▣':a.type==='Form'?'⌑':a.type==='Campaign'?'↗':'◇'}</div><div><h3>${esc(a.name)}</h3><p>${esc(a.type)} · ${esc(a.status)}</p></div></div><span>Open →</span></button>`).join("")}</div></div>`}
function projectData(x){return `<div class="tabs-page"><div class="dash-head"><div><div class="eyebrow">Data layer</div><h2 style="font-size:19px;margin:5px 0">Source of truth.</h2><p class="muted">Prototype data is local. Production can swap in a hosted database later.</p></div><button class="secondary-btn" onclick="toast('Table builder opened in prototype')">＋ New table</button></div><div class="panel"><div class="panel-head"><div><div class="eyebrow">Customers</div><h3>3 records</h3></div><button class="ghost-btn" onclick="setMode('Analyze');setTab('ai')">Ask AI ↗</button></div><div class="table" style="margin-top:12px"><div class="table-grid"><div class="th">Name</div><div class="th">Status</div><div class="th">Last order</div><div class="th">Total spent</div><div>Rahul S.</div><div><span class="badge good">Active</span></div><div>Yesterday</div><div>₹1,099</div><div>Mira K.</div><div><span class="badge good">Active</span></div><div>4 days ago</div><div>₹799</div><div>Ayaan P.</div><div><span class="badge">Lead</span></div><div>—</div><div>₹0</div></div></div></div></div>`}
function projectAutomations(x){const auto=x.automations||defaultAutomations();return `<div class="tabs-page"><div class="dash-head"><div><div class="eyebrow">Automation engine</div><h2 style="font-size:19px;margin:5px 0">Let the system keep moving.</h2></div><button class="primary-btn" onclick="createAutomation()">＋ Create automation</button></div><div class="asset-list">${auto.map((a,i)=>`<div class="asset"><div><h3 style="margin:0 0 4px;font-size:9px">${esc(a.name)}</h3><p>${esc(a.flow)}</p></div><span class="badge ${a.active?'good':''}">${a.active?'Active':'Draft'}</span></div>`).join("")}</div><div class="notice">In production, approved automations can run through real triggers, integrations and agent permissions.</div></div>`}
function defaultAutomations(){return[{name:"New customer",flow:"Create customer → send welcome → follow-up in 2 days",active:true},{name:"Booking created",flow:"Create order → confirmation → reminder",active:true},{name:"Lead untouched",flow:"Wait 48h → create follow-up task",active:false}]}
function projectAnalytics(x){const vals=[30,48,37,56,44,72,64,86];return `<div class="tabs-page"><div class="dash-head"><div><div class="eyebrow">Analytics</div><h2 style="font-size:19px;margin:5px 0">Is the project working?</h2></div><button class="secondary-btn" onclick="toast('Analytics export prepared')">Export</button></div><div class="analytics-cards"><div class="analytics-card"><span>Leads</span><strong>${x.metrics.leads}</strong></div><div class="analytics-card"><span>Customers</span><strong>${x.metrics.customers}</strong></div><div class="analytics-card"><span>Revenue</span><strong>${money(x.metrics.revenue)}</strong></div><div class="analytics-card"><span>Expenses</span><strong>${money(x.metrics.expenses)}</strong></div></div><div class="panel"><div class="eyebrow">Activity</div><div class="chart">${vals.map(v=>`<div class="bar" style="height:${v}%"></div>`).join("")}</div></div><div class="panel"><div class="eyebrow">AI interpretation</div><h3 style="font-size:14px;margin:5px 0">${esc(x.insight||'Build the smallest useful version, then use actual user behavior to choose the next iteration.')}</h3></div></div>`}
function fullAI(x){return `<div class="tabs-page"><div class="panel"><div class="panel-head"><div><div class="eyebrow">AI Co-Founder</div><h1 class="page-title" style="font-size:25px">Operate the project with AI.</h1><p class="page-sub">Persistent context: ${esc(x.name)} · ${esc(x.type)} · ${state.model} model</p></div><button class="secondary-btn" onclick="clearChat()">Clear</button></div><div class="mode-row" style="margin:14px 0">${["Discuss","Plan","Build","Analyze","Fix","Research","Execute"].map(m=>`<button class="mode ${state.mode===m?'active':''}" onclick="setMode('${m}')">${m}</button>`).join("")}</div><div class="chat" style="min-height:420px">${state.chat.map(chatMsg).join("")}</div><div class="chat-compose"><textarea id="fullInput" placeholder="Ask anything about your project or tell the AI what to do…"></textarea><div class="chat-bottom"><div class="tool-left"><button class="tool-btn" onclick="openAttachment()">📎 Attach</button><button class="tool-btn" onclick="openAISettings()">⚙ Model & settings</button></div><button class="run-btn" onclick="sendChat('fullInput')">Send ↑</button></div></div></div></div>`}
function versions(x){return `<div class="tabs-page"><div class="dash-head"><div><div class="eyebrow">Version history</div><h2 style="font-size:19px;margin:5px 0">Safe changes. Easy recovery.</h2></div><button class="primary-btn" onclick="openVersionModal()">＋ New branch</button></div><div class="timeline">${x.versions.map(v=>`<div class="timeline-row"><div class="timeline-mark"></div><div><strong>${esc(v.name)}</strong><p>${esc(v.detail)}</p></div><span class="badge" style="margin-left:auto">${esc(v.time)}</span></div>`).join("")}</div></div>`}
function selectProject(){return `<div class="panel" style="max-width:720px;margin:auto;text-align:center;padding:50px"><div class="eyebrow">Select a project</div><h2 style="font-size:22px;margin:8px 0">Open a project to use this area.</h2><p class="muted">Your project keeps the builder, data, assets, automation and AI context together.</p><button class="primary-btn" onclick="setView('projects')">Open projects →</button></div>`}
function globalAssets(){const all=state.projects.flatMap(pr=>(pr.assets||[]).map(a=>({...a,project:pr.name})));return `<div class="max"><div class="eyebrow">Assets</div><h1 class="page-title">Everything you've created.</h1><p class="page-sub">Global library for your project outputs.</p><div class="asset-list" style="margin-top:20px">${all.length?all.map(a=>`<div class="asset"><div><h3>${esc(a.name)}</h3><p>${esc(a.type)} · ${esc(a.project)}</p></div><span class="badge">${esc(a.status)}</span></div>`).join(""):`<div class="panel" style="text-align:center;padding:40px">No generated assets yet.</div>`}</div></div>`}
function settings(){return `<div class="max"><div class="eyebrow">Settings</div><h1 class="page-title">Workspace settings</h1><p class="page-sub">Control the experience, model defaults and prototype state.</p><div class="settings-grid" style="margin-top:20px"><div class="panel"><div class="setting"><div><strong>Reduce motion</strong><p>Minimize transitions and animation.</p></div><button class="toggle ${state.reduceMotion?'on':''}" onclick="toggleSetting('reduceMotion')"><i></i></button></div><div class="setting"><div><strong>Compact workspace</strong><p>Fit more information into project screens.</p></div><button class="toggle ${state.compact?'on':''}" onclick="toggleSetting('compact')"><i></i></button></div><div class="setting"><div><strong>Default model</strong><p>New conversations start with ${esc(state.model)}.</p></div><button class="secondary-btn" onclick="openAISettings()">Change</button></div><div class="setting"><div><strong>Reset showcase data</strong><p>Return the prototype to its demo-ready state.</p></div><button class="secondary-btn" onclick="resetDemo()">Reset</button></div></div><div class="panel"><div class="eyebrow">Plan</div><h2 style="font-size:22px;margin:7px 0">${esc(state.plan)}</h2><div class="metric"><span>AI credits</span><strong>${state.credits}</strong><small>Prototype allowance</small></div><button class="primary-btn" style="width:100%;margin-top:10px" onclick="openUpgrade()">See plans →</button></div></div></div>`}
async function startPrompt(text){
  text=String(text||"").trim();
  if(!text){toast('Describe what you want to make happen first.');return}
  const submit=document.activeElement; if(submit) submit.disabled=true;
  toast('Understanding your ambition…');
  try{
    const body={action:"blueprint",prompt:text,mode:state.mode,model:state.model,attachments:state.attachments};
    const r=await fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});
    const data=await r.json();
    if(data.ok && data.blueprint){
      createProjectFromBlueprint(text,data.blueprint);
      toast("AI blueprint ready");
    }else{
      createProject(text);
      toast(data.error?"AI unavailable — local prototype used":"Blueprint created");
    }
  }catch(e){
    createProject(text);
    toast("AI unavailable — local prototype used");
  }finally{ if(submit) submit.disabled=false; }
}
function createProjectFromBlueprint(prompt,b){
  const lower=prompt.toLowerCase();
  const type=b.type||((lower.includes("game")?"Game":lower.includes("saas")||lower.includes("app")?"Software":lower.includes("youtube")||lower.includes("creator")?"Creator":lower.includes("store")||lower.includes("shop")?"Commerce":lower.includes("service")||lower.includes("sneaker")?"Local service":"Project"));
  const pr={id:id(),name:b.name||"New Ambition",type,goal:b.goal||prompt,prompt,progress:24,targetCount:20,metrics:{customers:0,leads:0,revenue:0,expenses:0},nextAction:b.nextAction||"Validate the first useful outcome with 5 real people.",insight:b.insight||b.summary||"Start with the smallest useful system and learn from real outcomes.",systems:(b.systems||[]).map(s=>({name:s.name,purpose:s.purpose,done:false,outputs:s.outputs||[]})),milestones:(b.milestones||[]).map((m,i)=>({name:m.name,detail:m.detail,done:i===0})),tasks:(b.tasks||[]).map(t=>({text:t.text,done:false,priority:t.priority||"Medium",tag:t.tag||"Execution"})),assets:(b.assets||[]).map(a=>({name:a.name,type:a.type||"Generated",status:"Draft"})),pages:b.pages||[],dataTables:b.dataTables||[],automations:(b.automations||[]).map(a=>({name:a.name,flow:(a.trigger||"Trigger")+" → "+(a.action||"Action"),active:false})),versions:[{name:"AI blueprint",detail:"Generated from the ambition using the current AI model.",time:"Just now"}],activity:[{time:"Just now",text:"AI created a project blueprint"}]};
  if(!pr.systems.length) pr.systems=systemsFor(type);
  if(!pr.milestones.length) pr.milestones=[{name:"Understand the outcome",detail:"Define the result and constraints.",done:true},{name:"Build the minimum useful system",detail:"Generate the core experience and assets.",done:false},{name:"Launch the first real test",detail:"Put it in front of real people.",done:false},{name:"Learn and iterate",detail:"Use outcomes to improve the system.",done:false}];
  if(!pr.tasks.length) pr.tasks=[{text:"Validate the core outcome with 5 real people",done:false,priority:"High",tag:"Validation"},{text:"Create the first usable version",done:false,priority:"High",tag:"Build"},{text:"Set up one acquisition loop",done:false,priority:"Medium",tag:"Growth"},{text:"Define one weekly success metric",done:false,priority:"Medium",tag:"Analytics"}];
  if(!pr.assets.length) pr.assets=[{name:"Project blueprint",type:"Strategy",status:"Ready"},{name:"Launch checklist",type:"Operations",status:"Ready"}];
  state.projects.unshift(pr);state.activeProjectId=pr.id;state.tab="overview";state.view="build";state.chat=[{role:"ai",text:`I turned your ambition into a ${type.toLowerCase()} blueprint. I identified the systems, milestones, tasks, assets and launch requirements needed to move it forward.`}];state.attachments=[];state.credits=Math.max(0,state.credits-3);save();render();
}

function createProject(prompt){const lower=prompt.toLowerCase();let type="Project";if(lower.includes('game'))type="Game";else if(lower.includes('saas')||lower.includes('app')||lower.includes('software'))type="Software";else if(lower.includes('creator')||lower.includes('youtube')||lower.includes('content'))type="Creator";else if(lower.includes('store')||lower.includes('shop')||lower.includes('product'))type="Commerce";else if(lower.includes('service')||lower.includes('sneaker'))type="Local service";else if(lower.includes('marketplace'))type="Marketplace";const names={"Local service":"New Local Service","Software":"New SaaS","Creator":"Creator Launch","Game":"Game Launch","Commerce":"Online Store","Marketplace":"Marketplace Build","Project":"New Ambition"};const pr={id:id(),name:names[type],type,goal:trim(prompt),prompt,progress:18,targetCount:20,metrics:{customers:0,leads:0,revenue:0,expenses:0},nextAction:"Validate the core outcome with 5 real people.",insight:"The fastest route is to build the smallest useful version first, then use real feedback to guide the next iteration.",systems:systemsFor(type),milestones:[{name:"Understand the outcome",detail:"Define the result and constraints.",done:true},{name:"Build the minimum useful system",detail:"Generate the core experience and required assets.",done:false},{name:"Launch the first real test",detail:"Put the project in front of real people.",done:false},{name:"Learn and iterate",detail:"Use outcomes to improve the system.",done:false}],tasks:[{text:"Validate the core outcome with 5 real people",done:false,priority:"High",tag:"Validation"},{text:"Create the first usable version",done:false,priority:"High",tag:"Build"},{text:"Set up one acquisition loop",done:false,priority:"Medium",tag:"Growth"},{text:"Define one weekly success metric",done:false,priority:"Medium",tag:"Analytics"}],assets:[{name:"Project blueprint",type:"Strategy",status:"Ready"},{name:"Launch checklist",type:"Operations",status:"Ready"},{name:"First outreach pack",type:"Campaign",status:"Draft"}],automations:defaultAutomations(),versions:[{name:"Initial blueprint",detail:"Created project architecture from the ambition.",time:"Now"}],activity:[]};state.projects.unshift(pr);state.activeProjectId=pr.id;state.tab='overview';state.view='build';state.chat=[{role:'ai',text:`I understand the ambition. I created a ${type.toLowerCase()} project with a blueprint, milestones, first tasks and starter assets. Next, I can build the actual working pieces.`}];state.attachments=[];state.credits=Math.max(0,state.credits-2);save();render();toast('Project created — blueprint ready.')} 
function trim(t){t=String(t).trim();return t.length>76?t.slice(0,73)+'…':t}
function systemsFor(type){const base=[{name:'Strategy',icon:'◈',summary:'Goal, audience, positioning and success criteria.',status:'ready',items:['Outcome + constraints','Audience / user','Success metric']},{name:'Product',icon:'▣',summary:'The smallest useful experience that delivers the outcome.',status:'ready',items:['Core experience','User journey','MVP scope']},{name:'Growth',icon:'↗',summary:'How the project gets its first users or customers.',status:'in-progress',items:['Acquisition loop','Messaging','First users']},{name:'Operations',icon:'◒',summary:'Processes, quality checks and repeatable workflows.',status:'in-progress',items:['Workflow','Quality checks','Next actions']},{name:'Finance',icon:'₹',summary:'Budget, costs, pricing and measurable targets.',status:'ready',items:['Budget','Costs','Targets']},{name:'Analytics',icon:'◫',summary:'Metrics and feedback loops for continuous improvement.',status:'in-progress',items:['Key metrics','Events','Weekly review']}];if(type==='Game')base[0].summary='Audience, hook, core loop and monetization.';if(type==='Creator')base[0].summary='Niche, audience, positioning and content thesis.';return base}
function openProject(x){state.activeProjectId=x;state.view='build';state.tab='overview';state.chat=[{role:'ai',text:`Project loaded. I know its goal, blueprint, tasks, assets and history.`}];save();render()}
function simulateBuild(){const x=p();if(!x){toast('Create or open a project first.');return}const steps=['Understanding project context','Planning dependencies','Generating usable assets','Updating the live preview','Running quality checks'];let i=0;toast(steps[0]+'…');const timer=setInterval(()=>{i++;if(i<steps.length)toast(steps[i]+'…');else{clearInterval(timer);x.progress=Math.min(100,x.progress+9);x.assets.unshift({name:'AI build package',type:'Generated',status:'Ready'});x.versions.unshift({name:'AI build update',detail:'Built and verified a project update.',time:'Just now'});x.activity.unshift({time:'Just now',text:'AI built and verified a project update'});state.credits=Math.max(0,state.credits-2);save();render();toast('Build complete — the project moved forward.')}},450)}
function executeNext(){const x=p();if(!x)return;x.tasks[0].done=true;x.progress=Math.min(100,x.progress+6);x.nextAction='Test the next milestone with a small real-world action.';save();render();toast('Next action completed in the prototype.')}
function toggleTask(i){const x=p();if(!x)return;x.tasks[i].done=!x.tasks[i].done;x.progress=Math.min(100,Math.max(18,18+Math.round(x.tasks.filter(t=>t.done).length/x.tasks.length*82)));save();render()}
function addTask(){const text=prompt('Task name');if(!text)return;p().tasks.push({text,done:false,priority:'Medium',tag:'Custom'});save();render();toast('Task added')}
function generateAsset(){const x=p();if(!x)return;const names=['Offer sheet','Customer intake form','Launch post pack','Weekly review','Brand starter','Setup guide'];const name=names[x.assets.length%names.length];x.assets.unshift({name,type:'Generated',status:'Draft'});x.activity.unshift({time:'Just now',text:'AI generated '+name});state.credits=Math.max(0,state.credits-1);save();render();toast(name+' generated.')}
function previewAsset(i){const a=p()?.assets[i];if(!a)return;openModal(`<div class="modal-head"><div><div class="eyebrow">Generated asset</div><h2>${esc(a.name)}</h2><p>${esc(a.type)} · ${esc(a.status)}</p></div><button class="icon-btn" onclick="closeModal()">×</button></div><div class="attach-drop"><strong>LIVE PREVIEW</strong><p>In the production build this opens the full editor/exporter. The prototype keeps the asset connected to project memory.</p><div class="file-list"><div class="file-row"><span>✓ Generated from project context</span><span class="badge good">Ready</span></div><div class="file-row"><span>✓ Available to AI Co-Founder</span><span class="badge good">Synced</span></div></div></div><div class="modal-actions"><button class="secondary-btn" onclick="closeModal()">Close</button><button class="primary-btn" onclick="toast('Editor opened');closeModal()">Open editor →</button></div>`)}
async function sendChat(inputId){
  const el=document.getElementById(inputId); if(!el||!el.value.trim())return;
  const text=el.value.trim(); const x=p(); state.chat.push({role:"user",text}); el.value=""; render();
  state.chat.push({role:"ai",text:"Thinking through your project…"}); render();
  try{
    const r=await fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"chat",prompt:text,mode:state.mode,model:state.model,project:x,attachments:state.attachments})});
    const data=await r.json(); const idx=state.chat.length-1;
    state.chat[idx]={role:"ai",text:data.ok?data.text:aiAnswer(text,x)};
  }catch(e){ const idx=state.chat.length-1; state.chat[idx]={role:"ai",text:aiAnswer(text,x)}; }
  state.credits=Math.max(0,state.credits-1); if(x)x.activity.unshift({time:"Just now",text:"AI Co-Founder responded"}); state.attachments=[]; save(); render();
}
function aiAnswer(t,x){const s=t.toLowerCase();if(s.includes('what should')||s.includes('next'))return `The next best action is: ${x?.nextAction||'validate the core outcome with five real people.'} I would not add more complexity until you have a real signal.`;if(s.includes('build'))return `I’d build the smallest usable version first. For this project that means the core experience, the minimum data model, one measurable success event, and the launch instructions. I can keep the rest behind the next milestone.`;if(s.includes('marketing')||s.includes('customer'))return `Focus on one acquisition loop: a clear offer, one proof asset, one outreach script and a follow-up task. Once the conversion signal is real, scale it.`;if(s.includes('analy'))return `The project currently sits at ${x?.progress||0}% progress. The strongest signal to watch is whether the next action produces measurable movement toward the main goal.`;if(s.includes('fix'))return `I’d inspect the most recent change, verify dependencies, and roll back only the affected part. In production, the verification layer would run tests before publishing.`;return `I’ve got the project context. I’d turn that request into one concrete change, one measurable outcome and one next action so the project keeps moving.`}
function clearChat(){state.chat=[];save();render();toast('Chat cleared')}
function setMode(m){state.mode=m;save();render()}
function setComposerMode(m){state.mode=m;save();render()}
function setModel(m){state.model=m;save();render();toast('Model set to '+m)}
function toggleSelector(id){document.querySelectorAll('.selector-menu').forEach(x=>x.classList.add('hidden'));document.getElementById(id)?.classList.toggle('hidden')}
function openAttachment(){document.getElementById('globalFileInput').click()}
document.getElementById('globalFileInput').addEventListener('change',e=>addFiles([...e.target.files]))
function addFiles(files){files.forEach(f=>state.attachments.push({name:f.name,size:f.size,kind:f.type.startsWith('image/')?'image':'file'}));save();render();toast(files.length+' attachment'+(files.length===1?'':'s')+' added')}
function removeAttachment(i){state.attachments.splice(i,1);save();render()}
function openContextMenu(){openModal(`<div class="modal-head"><div><div class="eyebrow">Project context</div><h2>Attach context</h2><p>Choose what the AI should use for this request.</p></div><button class="icon-btn" onclick="closeModal()">×</button></div><div class="file-list"><div class="file-row"><span>✓ Project blueprint</span><span class="badge good">Included</span></div><div class="file-row"><span>✓ Tasks + milestones</span><span class="badge good">Included</span></div><div class="file-row"><span>✓ Generated assets</span><span class="badge">Optional</span></div><div class="file-row"><span>✓ Analytics + project data</span><span class="badge">Optional</span></div></div><div class="modal-actions"><button class="primary-btn" onclick="closeModal();toast('Project context attached')">Attach context →</button></div>`)}
function openAISettings(){openModal(`<div class="modal-head"><div><div class="eyebrow">AI settings</div><h2>How should the AI work?</h2><p>These are prototype controls; production will route them to actual model providers.</p></div><button class="icon-btn" onclick="closeModal()">×</button></div><div class="file-list"><div class="setting"><div><strong>Model</strong><p>${esc(state.model)}</p></div><button class="secondary-btn" onclick="closeModal();openModelPicker()">Change</button></div><div class="setting"><div><strong>Use project memory</strong><p>Keep decisions, context and history attached.</p></div><span class="badge good">On</span></div><div class="setting"><div><strong>Use attached files</strong><p>Include uploaded files in the request context.</p></div><span class="badge good">On</span></div><div class="setting"><div><strong>Ask before major changes</strong><p>Require approval for consequential actions.</p></div><span class="badge good">On</span></div></div><div class="modal-actions"><button class="primary-btn" onclick="closeModal()">Done</button></div>`)}
function openModelPicker(){openModal(`<div class="modal-head"><div><div class="eyebrow">Model selector</div><h2>Choose the generation profile.</h2></div><button class="icon-btn" onclick="closeModal()">×</button></div><div class="file-list">${modelOptions().map(m=>`<button class="asset" onclick="setModel('${m.n}');closeModal()"><div><h3>${m.n}</h3><p>${m.d}</p></div><span class="badge ${state.model===m.n?'good':''}">${state.model===m.n?'Selected':'Use'}</span></button>`).join('')}</div>`)}
function openCommand(){openModal(`<div class="command"><div class="command-input"><span>⌕</span><input id="cmdInput" autofocus placeholder="Search, navigate, build…" oninput="filterCmd(this.value)"/><span class="mini">ESC</span></div><div id="cmdResults" class="command-results">${commandItems().map(c=>`<button onclick="commandGo('${c.v}')">${c.i}　${c.l}</button>`).join('')}</div></div>`)}
function commandItems(){return[["home","⌂","Go home"],["projects","▦","Open projects"],["build","✦","Open builder"],["assets","◇","Open assets"],["analytics","◒","Open analytics"],["ai","◎","Open AI Co-Founder"],["settings","⚙","Open settings"]].map(x=>({v:x[0],i:x[1],l:x[2]}))}
function filterCmd(q){const r=document.getElementById('cmdResults');r.innerHTML=commandItems().filter(c=>c.l.toLowerCase().includes(q.toLowerCase())).map(c=>`<button onclick="commandGo('${c.v}')">${c.i}　${c.l}</button>`).join('')||'<div class="muted" style="padding:20px;text-align:center">Nothing found.</div>'}
function commandGo(v){closeModal();setView(v)}
function openUpgrade(){openModal(`<div class="modal-head"><div><div class="eyebrow">Plans</div><h2>Unlock the full creation OS.</h2><p>The prototype uses mock checkout. Before launch, connect a real server-side payment provider.</p></div><button class="icon-btn" onclick="closeModal()">×</button></div><div class="pricing"><div class="price"><span class="label">FREE</span><strong>₹0</strong><ul><li>1 active project</li><li>20 AI credits</li><li>Blueprint + core builder</li><li>Local prototype storage</li></ul><button class="secondary-btn" style="width:100%">Current plan</button></div><div class="price featured"><span class="label">PRO</span><strong>₹399<small>/month</small></strong><ul><li>More AI generation</li><li>Advanced models</li><li>Agents + automations</li><li>Deployment tools</li><li>Priority generation</li></ul><button class="primary-btn" style="width:100%" onclick="upgrade('Pro')">Continue with Pro →</button></div><div class="price"><span class="label">MAX</span><strong>₹999<small>/month</small></strong><ul><li>Everything in Pro</li><li>Highest limits</li><li>Advanced agents</li><li>Team collaboration</li><li>Priority infrastructure</li></ul><button class="secondary-btn" style="width:100%" onclick="upgrade('Max')">Choose Max</button></div></div>`)}
function upgrade(plan){state.plan=plan;state.credits=plan==='Max'?300:120;save();closeModal();render();toast('Demo upgraded to '+plan)}
function openLaunchModal(){const x=p();openModal(`<div class="modal-head"><div><div class="eyebrow">Ready state</div><h2>${x.progress>=85?'Ready to launch':'Launch readiness'}</h2><p>We check the visible prototype state and tell the user what remains.</p></div><button class="icon-btn" onclick="closeModal()">×</button></div><div class="file-list">${[['Core system',x.progress>=40],['Tasks / milestones',x.tasks.some(t=>!t.done)===false],['Quality checks',true],['External setup',false]].map(v=>`<div class="file-row"><span>${v[1]?'✓':'○'} ${v[0]}</span><span class="badge ${v[1]?'good':''}">${v[1]?'Complete':'Needs action'}</span></div>`).join('')}</div><div class="notice" style="margin-top:10px">Anything requiring an external account, payment provider, domain or third-party permission is shown as an exact setup step rather than pretending the AI completed it.</div><div class="modal-actions"><button class="primary-btn" onclick="closeModal();toast('Launch checklist opened')">Continue setup →</button></div>`)}
function openVersionModal(){openModal(`<div class="modal-head"><div><div class="eyebrow">Version control</div><h2>Create a safe branch.</h2><p>Production stays untouched while you experiment.</p></div><button class="icon-btn" onclick="closeModal()">×</button></div><div class="form-stack"><label>Branch name<input id="branchName" value="experiment-${Date.now().toString().slice(-4)}"/></label><label>Purpose<textarea id="branchPurpose" placeholder="What are you testing?"></textarea></label></div><div class="modal-actions"><button class="secondary-btn" onclick="closeModal()">Cancel</button><button class="primary-btn" onclick="createBranch()">Create branch →</button></div>`)}
function createBranch(){const x=p();if(x)x.versions.unshift({name:document.getElementById('branchName').value||'Untitled branch',detail:document.getElementById('branchPurpose').value||'Experiment branch created from current state.',time:'Just now'});save();closeModal();render();toast('Branch created')}
function createAutomation(){const x=p();if(!x)return;x.automations.unshift({name:'AI-created workflow',flow:'Trigger → conditions → action → report to project',active:false});save();render();toast('Automation draft created')}
function fillChat(v){const e=document.getElementById('miniInput');if(e){e.value=v;e.focus()}}
function toggleSide(){state.sidebar=!state.sidebar;render()}
function toggleSetting(k){state[k]=!state[k];save();render()}
function resetDemo(){localStorage.removeItem(KEY);state=merge(blank,{});seed();render();toast('Showcase reset')}
function closeModal(){document.getElementById('modalRoot').innerHTML=''}
function openModal(html){document.getElementById('modalRoot').innerHTML=`<div class="modal-back" onclick="closeModal()"></div><div class="modal">${html}</div>`}
function openWorkspaceMenu(){toast('Workspace switching is reserved for team workspaces.')}
window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommand()}if(e.key==='Escape')closeModal()})
const drop=document.body;drop.addEventListener('dragover',e=>{const c=document.querySelector('.attach-drop');if(c){e.preventDefault();c.classList.add('drag')}});drop.addEventListener('dragleave',()=>document.querySelector('.attach-drop')?.classList.remove('drag'));drop.addEventListener('drop',e=>{if(e.dataTransfer?.files?.length){e.preventDefault();addFiles([...e.dataTransfer.files]);document.querySelector('.attach-drop')?.classList.remove('drag')}})
function useTemplate(i){startPrompt(templates[i].prompt)}
function seed(){if(state.projects.length)return;createProject("I want to start a sneaker cleaning service with ₹20,000 in Pune.");state.projects[0].name='Sneaker Cleaning Launch';state.projects[0].progress=42;state.projects[0].metrics={customers:3,leads:18,revenue:2497,expenses:620};state.projects[0].tasks[0].done=true;state.projects[0].nextAction='Contact 10 nearby sneaker owners.';state.projects[0].insight='You have an early signal. Focus on turning the current offer into a repeatable local acquisition loop.';state.projects[0].activity=[{time:'Just now',text:'AI created your execution workspace'}];state.view='home';state.activeProjectId=state.projects[0].id;state.chat=[];save()}
seed();render();
