(() => {
  'use strict';
  const HIDE = new Set(['Activity','Research','Agents','Integrations','Resources','Templates']);
  const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const CSS = `
  .px-clean-sidebar{position:fixed;z-index:9990;left:0;top:0;bottom:0;width:248px;background:#fafbfc;border-right:1px solid #e7e9ed;padding:28px 16px 18px;display:flex;flex-direction:column;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#151922}
  .px-clean-brand{font-size:24px;font-weight:750;letter-spacing:-.055em;padding:0 12px 30px}
  .px-clean-nav{display:grid;gap:5px}
  .px-clean-nav button,.px-clean-assistant{appearance:none;border:0;background:transparent;width:100%;display:flex;align-items:center;gap:12px;text-align:left;padding:11px 12px;border-radius:10px;color:#5e6675;font:500 14px inherit;cursor:pointer}
  .px-clean-nav button:hover,.px-clean-assistant:hover{background:#f0f2f5;color:#151922}
  .px-clean-nav button.active{background:#eef0f3;color:#151922;font-weight:650}
  .px-clean-icon{width:20px;text-align:center;font-size:17px;line-height:1;color:#242a34}
  .px-clean-divider{height:1px;background:#e7e9ed;margin:20px 6px 16px}
  .px-clean-label{padding:0 12px 9px;font-size:10px;font-weight:700;letter-spacing:.13em;text-transform:uppercase;color:#9aa1ad}
  .px-clean-assistant{border:1px solid #e1e4e9;background:#fff;box-shadow:0 1px 2px rgba(20,25,35,.03)}
  .px-clean-recent{display:grid;gap:2px;max-height:180px;overflow:auto}
  .px-clean-recent button{appearance:none;border:0;background:transparent;text-align:left;padding:8px 12px;border-radius:8px;color:#626a77;font:400 12px/1.35 inherit;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;cursor:pointer}
  .px-clean-recent button:hover{background:#f0f2f5;color:#151922}
  .px-clean-account{margin-top:auto;border:1px solid #e1e4e9;background:#fff;border-radius:12px;padding:12px;display:flex;align-items:center;gap:10px;cursor:pointer}
  .px-clean-avatar{width:34px;height:34px;border-radius:50%;display:grid;place-items:center;background:#e9edf2;color:#667080;font-weight:700}
  .px-clean-account-main{min-width:0;flex:1}.px-clean-account-name{display:block;font-size:13px;font-weight:650}.px-clean-account-plan{display:block;font-size:11px;color:#8b93a0;margin-top:2px}.px-clean-chevron{color:#8b93a0;font-size:18px}
  .px-clean-source-hidden{display:none!important}
  @media(min-width:801px){#appRoot{padding-left:248px!important}}
  @media(max-width:800px){.px-clean-sidebar{position:relative;width:100%;height:auto;min-height:0;border-right:0;border-bottom:1px solid #e7e9ed;padding:14px 12px 10px}.px-clean-brand{padding:2px 8px 12px}.px-clean-nav{grid-template-columns:repeat(4,1fr)}.px-clean-nav button{justify-content:center;flex-direction:column;gap:4px;padding:8px 4px;font-size:11px}.px-clean-divider,.px-clean-label,.px-clean-assistant,.px-clean-recent{display:none}.px-clean-account{position:absolute;right:12px;top:12px;width:auto;border:0;padding:0;background:transparent}.px-clean-account-main{display:none}.px-clean-chevron{display:none}.px-clean-avatar{width:32px;height:32px}}
  `;
  function injectCSS(){if(document.getElementById('px-clean-dashboard-style'))return;const s=document.createElement('style');s.id='px-clean-dashboard-style';s.textContent=CSS;document.head.appendChild(s)}
  function textElement(label){return [...document.querySelectorAll('#appRoot *')].find(el=>el.children.length===0&&(el.textContent||'').trim()===label)||null}
  function findSourceSidebar(){const labels=['Home','Projects','Analytics','Settings'];const els=labels.map(textElement).filter(Boolean);if(els.length<3)return null;let node=els[0].parentElement;while(node&&node!==document.body){const txt=node.textContent||'';if(labels.filter(x=>txt.includes(x)).length>=3){const r=node.getBoundingClientRect();if(r.width>70&&r.width<360&&r.height>250)return node}node=node.parentElement}return null}
  function getRecent(){const out=[];try{for(const key of ['builder_universal_v14','builder_state_v14']){const raw=localStorage.getItem(key);if(!raw)continue;const s=JSON.parse(raw);const list=Array.isArray(s.projects)?s.projects:[];for(const p of list){const title=String(p.title||p.name||p.intention||p.intent||'').split('\n')[0].trim();if(title&&!out.includes(title))out.push(title)}}}catch{}return out.slice(0,5)}
  function action(label){const el=textElement(label);if(el){(el.closest('button,a,[role="button"]')||el).click();return true}return false}
  function build(){if(document.querySelector('.px-clean-sidebar'))return true;const source=findSourceSidebar();if(!source)return false;source.classList.add('px-clean-source-hidden');const side=document.createElement('aside');side.className='px-clean-sidebar';const recent=getRecent();side.innerHTML=`<div class="px-clean-brand">ProjectX</div><nav class="px-clean-nav" aria-label="Main navigation"><button data-px-nav="Home" class="active"><span class="px-clean-icon">⌂</span><span>Home</span></button><button data-px-nav="Projects"><span class="px-clean-icon">□</span><span>Projects</span></button><button data-px-nav="Analytics"><span class="px-clean-icon">▥</span><span>Analytics</span></button><button data-px-nav="Settings"><span class="px-clean-icon">⚙</span><span>Settings</span></button></nav><div class="px-clean-divider"></div><div class="px-clean-label">Assistant</div><button class="px-clean-assistant" data-px-assistant><span class="px-clean-icon">✦</span><span>Assistant X</span></button><div class="px-clean-divider"></div><div class="px-clean-label">Recent</div><div class="px-clean-recent">${recent.length?recent.map(x=>`<button title="${esc(x)}">${esc(x)}</button>`).join(''):'<button>No recent creations</button>'}</div><button class="px-clean-account" data-px-account><span class="px-clean-avatar">P</span><span class="px-clean-account-main"><span class="px-clean-account-name">Pushkar</span><span class="px-clean-account-plan">Free Plan</span></span><span class="px-clean-chevron">›</span></button>`;document.body.appendChild(side);side.addEventListener('click',e=>{const nav=e.target.closest('[data-px-nav]');if(nav){const label=nav.dataset.pxNav;side.querySelectorAll('[data-px-nav]').forEach(x=>x.classList.toggle('active',x===nav));action(label);return}if(e.target.closest('[data-px-assistant]')){window.dispatchEvent(new CustomEvent('projectx:assistant-x'));return}if(e.target.closest('[data-px-account]')){action('Settings');return}const r=e.target.closest('.px-clean-recent button');if(r&&r.textContent!=='No recent creations')action(r.textContent.trim())});const sweep=()=>document.querySelectorAll('#appRoot *').forEach(el=>{if(el.children.length===0&&HIDE.has((el.textContent||'').trim()))(el.closest('button,a,[role="button"],li')||el).classList.add('px-clean-source-hidden')});sweep();new MutationObserver(sweep).observe(document.querySelector('#appRoot')||document.body,{subtree:true,childList:true});return true}
  function start(){injectCSS();if(build())return;let n=0;const timer=setInterval(()=>{n++;if(build()||n>80)clearInterval(timer)},250)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
