(()=>{'use strict';
const STYLE=`#px-game-output{border:1px solid #e1e5e9;border-radius:12px;background:#fff;padding:16px}#px-game-output .g-head{display:flex;justify-content:space-between;align-items:flex-start;gap:12px;margin-bottom:12px}#px-game-output .g-head h2{margin:0;font-size:21px;letter-spacing:-.035em}#px-game-output .g-head p{margin:5px 0 0;color:#7a838e;font-size:11px;line-height:1.5}#px-game-output .g-tools{display:flex;gap:7px;flex-wrap:wrap}#px-game-output button{border:1px solid #d9dee3;background:#fff;border-radius:7px;padding:8px 11px;font-size:11px;cursor:pointer}#px-game-output button.primary{background:#171a1f;color:#fff;border-color:#171a1f}#px-game-output .g-stage{border:1px solid #dfe3e7;border-radius:10px;overflow:hidden;background:#dff3ff;display:flex;justify-content:center}#px-game-output canvas{display:block;width:100%;max-width:760px;height:auto;background:#dff3ff}#px-game-output .g-help{margin-top:10px;color:#7a838e;font-size:11px;line-height:1.5}#px-game-output .g-badge{display:inline-flex;align-items:center;border:1px solid #dfe3e7;border-radius:999px;padding:4px 8px;font-size:10px;color:#68717d;margin-top:8px}`;
function install(){if(document.getElementById('px-game-style'))return;const s=document.createElement('style');s.id='px-game-style';s.textContent=STYLE;document.head.appendChild(s)}
function root(){return document.querySelector('#pxa')}
function title(){return (document.querySelector('#pxa .pxa-panel h1')?.textContent||'Game prototype').trim()}
function isGame(){const k=(document.querySelector('#pxa .pxa-kicker')?.textContent||'').toLowerCase();const h=title().toLowerCase();return k.includes('game')||/flappy|game|rpg|platformer|arcade|runner|pong|snake/.test(h)}
function stop(){window.__pxGameCleanup?.();window.__pxGameCleanup=null}
function outputHTML(){return `<div id="px-game-output"><div class="g-head"><div><h2>Playtest</h2><p>This is the live playable output for this game workspace, not just documentation.</p><span class="g-badge">Local prototype · no external assets</span></div><div class="g-tools"><button id="gRestart" class="primary">Restart</button><button id="gPause">Pause</button></div></div><div class="g-stage"><canvas id="gCanvas" width="760" height="430" aria-label="Playable game output"></canvas></div><div class="g-help">Click the game or press <b>Space</b> to flap. Avoid the pipes. This prototype is rendered directly in ProjectX; later the Build/Code flow can replace it with the user's generated implementation.</div></div>`}
function renderGame(){stop();const b=document.querySelector('#pbody');if(!b)return;b.innerHTML=outputHTML();const c=document.querySelector('#gCanvas');if(!c)return;const ctx=c.getContext('2d');let raf=0,running=false,paused=false,over=false,score=0,t=0,bird={x:170,y:210,vy:0,r:14},pipes=[];const W=c.width,H=c.height,gravity=.42,jump=-7.0,speed=2.6,gap=150,ground=H-34;
const reset=()=>{cancelAnimationFrame(raf);running=false;paused=false;over=false;score=0;t=0;bird={x:170,y:210,vy:0,r:14};pipes=[{x:520,gapY:170,passed:false}];draw()};
const flap=()=>{if(over){reset();start();return}if(!running)start();bird.vy=jump};
const hit=(p)=>{const top=p.gapY-gap/2,bottom=p.gapY+gap/2;return bird.x+bird.r>p.x&&bird.x-bird.r<p.x+52&&(bird.y-bird.r<top||bird.y+bird.r>bottom)};
const addPipe=()=>{const min=105,max=H-105;const gy=min+Math.random()*(max-min);pipes.push({x:W+20,gapY:gy,passed:false})};
const update=()=>{if(!running||paused||over){draw();return}bird.vy+=gravity;bird.y+=bird.vy;t+=1;pipes.forEach(p=>p.x-=speed);if(pipes[pipes.length-1].x<430)addPipe();if(pipes.length&&pipes[0].x<-70)pipes.shift();for(const p of pipes){if(!p.passed&&p.x+52<bird.x){p.passed=true;score++}if(hit(p)){over=true;running=false}}if(bird.y-bird.r<0||bird.y+bird.r>ground){over=true;running=false}draw();raf=requestAnimationFrame(update)};
const draw=()=>{ctx.clearRect(0,0,W,H);ctx.fillStyle='#dff3ff';ctx.fillRect(0,0,W,H);for(let i=0;i<7;i++){ctx.fillStyle='rgba(255,255,255,.65)';ctx.beginPath();ctx.arc(65+i*120,55+(i%3)*22,24,0,Math.PI*2);ctx.arc(90+i*120,53+(i%3)*22,18,0,Math.PI*2);ctx.fill()}for(const p of pipes){const top=p.gapY-gap/2,bottom=p.gapY+gap/2;ctx.fillStyle='#5b9b4c';ctx.fillRect(p.x,0,52,top);ctx.fillRect(p.x,bottom,52,ground-bottom);ctx.fillStyle='#4f8c42';ctx.fillRect(p.x-4,top-10,60,10);ctx.fillRect(p.x-4,bottom,60,10)}ctx.fillStyle='#6db44f';ctx.fillRect(0,ground,W,H-ground);ctx.fillStyle='#d5a344';ctx.fillRect(0,ground,W,5);ctx.save();ctx.translate(bird.x,bird.y);ctx.rotate(Math.max(-.5,Math.min(.9,bird.vy*.06)));ctx.fillStyle='#f4ca45';ctx.beginPath();ctx.arc(0,0,bird.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(7,-5,6,0,Math.PI*2);ctx.fill();ctx.fillStyle='#222';ctx.beginPath();ctx.arc(9,-5,2.3,0,Math.PI*2);ctx.fill();ctx.fillStyle='#e78f28';ctx.beginPath();ctx.moveTo(12,2);ctx.lineTo(25,6);ctx.lineTo(12,9);ctx.closePath();ctx.fill();ctx.restore();ctx.fillStyle='#171a1f';ctx.font='700 28px system-ui,sans-serif';ctx.textAlign='center';ctx.fillText(String(score),W/2,48);if(!running&&!over){ctx.fillStyle='rgba(255,255,255,.88)';ctx.fillRect(W/2-155,H/2-48,310,96);ctx.fillStyle='#171a1f';ctx.font='700 21px system-ui,sans-serif';ctx.fillText('Click or press Space',W/2,H/2-8);ctx.font='12px system-ui,sans-serif';ctx.fillStyle='#6f7884';ctx.fillText('Start the playable output',W/2,H/2+18)}if(over){ctx.fillStyle='rgba(255,255,255,.9)';ctx.fillRect(W/2-145,H/2-55,290,110);ctx.fillStyle='#171a1f';ctx.font='700 24px system-ui,sans-serif';ctx.fillText('Game over',W/2,H/2-12);ctx.font='12px system-ui,sans-serif';ctx.fillStyle='#6f7884';ctx.fillText(`Score ${score} · Click or Restart`,W/2,H/2+14)}};
const start=()=>{if(over)return;running=true;paused=false;raf=requestAnimationFrame(update)};const togglePause=()=>{paused=!paused;document.getElementById('gPause').textContent=paused?'Resume':'Pause';if(!paused&&running)raf=requestAnimationFrame(update);draw()};
const onKey=e=>{if(e.code==='Space'){e.preventDefault();flap()}};const onClick=e=>{if(e.target.closest('button'))return;flap()};
window.addEventListener('keydown',onKey);c.addEventListener('click',onClick);document.getElementById('gRestart').onclick=()=>reset();document.getElementById('gPause').onclick=()=>togglePause();reset();window.__pxGameCleanup=()=>{cancelAnimationFrame(raf);window.removeEventListener('keydown',onKey);c.removeEventListener('click',onClick)};
}
function patch(){install();const r=root();if(!r||!isGame())return;const tabs=r.querySelector('.pxa-tabs');if(!tabs)return;let tab=tabs.querySelector('[data-output-tab]');if(!tab){tab=document.createElement('button');tab.className='pxa-tab';tab.dataset.outputTab='1';tab.textContent='Playtest';tabs.insertBefore(tab,tabs.children[1]||null);tab.onclick=e=>{e.preventDefault();e.stopPropagation();tabs.querySelectorAll('.pxa-tab').forEach(x=>x.classList.remove('active'));tab.classList.add('active');renderGame()}}}
const mo=new MutationObserver(()=>{clearTimeout(window.__pxGameTimer);window.__pxGameTimer=setTimeout(patch,20)});mo.observe(document.body,{subtree:true,childList:true});setInterval(patch,500);patch();
})();