import { createClient } from "npm:@supabase/supabase-js@2";
import { corsHeaders, json } from "../_shared/cors.ts";
const URL=Deno.env.get("SUPABASE_URL")!, ANON=Deno.env.get("SUPABASE_ANON_KEY")||Deno.env.get("SUPABASE_PUBLISHABLE_KEY")!, SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||Deno.env.get("SUPABASE_SECRET_KEY")!;
const APP_ORIGIN=(Deno.env.get("APP_ORIGIN")||"https://pushlabs-tech.github.io").replace(/\/$/,""), RESEND=Deno.env.get("RESEND_API_KEY")||"", FROM=Deno.env.get("INVITE_FROM_EMAIL")||"ProjectX <noreply@example.com>";
const admin=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
async function auth(req:Request){const h=req.headers.get("Authorization");if(!h)throw new Error("SIGN_IN_REQUIRED");const c=createClient(URL,ANON,{global:{headers:{Authorization:h}}});const {data,error}=await c.auth.getUser();if(error||!data.user)throw new Error("INVALID_SESSION");return data.user;}
async function hash(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("");}
async function invite(u:any,b:any){const ws=String(b.workspaceId||""),email=String(b.email||"").trim().toLowerCase(),role=String(b.role||"editor");if(!ws||!email)throw new Error("WORKSPACE_AND_EMAIL_REQUIRED");const {data:m}=await admin.from("workspace_members").select("role").eq("workspace_id",ws).eq("user_id",u.id).maybeSingle();if(!m||!["owner","admin"].includes(m.role))throw new Error("FORBIDDEN");if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error("INVALID_EMAIL");const raw=crypto.randomUUID().replaceAll("-","")+crypto.randomUUID().replaceAll("-",""),tokenHash=await hash(raw),expires=new Date(Date.now()+7*86400000).toISOString();await admin.from("workspace_invitations").delete().eq("workspace_id",ws).eq("email",email).is("accepted_at",null);const {data:i,error}=await admin.from("workspace_invitations").insert({workspace_id:ws,email,role,token_hash:tokenHash,invited_by:u.id,expires_at:expires}).select("id,expires_at,role").single();if(error)throw error;const link=`${APP_ORIGIN}/?invite=${encodeURIComponent(raw)}`;if(RESEND){await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${RESEND}`,"Content-Type":"application/json"},body:JSON.stringify({from:FROM,to:[email],subject:"You’re invited to a ProjectX workspace",html:`<p>You’ve been invited to collaborate in ProjectX.</p><p><a href="${link}">Accept invitation</a></p><p>This invitation expires in 7 days.</p>`})});}return {invitation:i,inviteUrl:link,emailSent:!!RESEND};}
async function accept(u:any,raw:string){if(!raw)throw new Error("INVITE_TOKEN_REQUIRED");const h=await hash(raw);const {data:i,error}=await admin.from("workspace_invitations").select("*").eq("token_hash",h).maybeSingle();if(error||!i)throw new Error("INVITATION_NOT_FOUND");if(i.accepted_at||new Date(i.expires_at).getTime()<Date.now())throw new Error("INVITATION_EXPIRED");if(String(i.email).toLowerCase()!==String(u.email||"").toLowerCase())throw new Error("INVITATION_EMAIL_MISMATCH");const {error:e}=await admin.from("workspace_members").upsert({workspace_id:i.workspace_id,user_id:u.id,role:i.role},{onConflict:"workspace_id,user_id"});if(e)throw e;await admin.from("workspace_invitations").update({accepted_at:new Date().toISOString(),accepted_by:u.id}).eq("id",i.id);return {workspaceId:i.workspace_id,role:i.role};}
async function list(u:any,ws:string){const {data:m}=await admin.from("workspace_members").select("role").eq("workspace_id",ws).eq("user_id",u.id).maybeSingle();if(!m)throw new Error("FORBIDDEN");const {data,error}=await admin.from("workspace_members").select("user_id,role,created_at").eq("workspace_id",ws);if(error)throw error;return data||[];}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});try{const u=await auth(req),b=await req.json().catch(()=>({})),a=String(b.action||"");if(a==="invite")return json({ok:true,...await invite(u,b)});if(a==="accept")return json({ok:true,...await accept(u,String(b.token||""))});if(a==="members")return json({ok:true,members:await list(u,String(b.workspaceId||""))});throw new Error("Unknown action");}catch(e){return json({ok:false,error:e instanceof Error?e.message:String(e)},400);}});