import { createClient } from "npm:@supabase/supabase-js@2";
import { corsHeaders, json } from "../_shared/cors.ts";
import { encryptSecret, decryptSecret } from "../_shared/crypto.ts";

const URL=Deno.env.get("SUPABASE_URL")!;
const ANON=Deno.env.get("SUPABASE_ANON_KEY")||Deno.env.get("SUPABASE_PUBLISHABLE_KEY")!;
const SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||Deno.env.get("SUPABASE_SECRET_KEY")!;
const CLIENT_ID=Deno.env.get("GITHUB_OAUTH_CLIENT_ID")||Deno.env.get("GITHUB_CLIENT_ID")||"";
const CLIENT_SECRET=Deno.env.get("GITHUB_OAUTH_CLIENT_SECRET")||Deno.env.get("GITHUB_CLIENT_SECRET")||"";
const REDIRECT=Deno.env.get("GITHUB_REDIRECT_URI")||"https://homgaryumqbrnjcfkezi.supabase.co/functions/v1/github";
const ORIGIN=(Deno.env.get("APP_ORIGIN")||"https://pushlabs-tech.github.io").replace(/\/$/,"");
const admin=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});

async function auth(req:Request){const h=req.headers.get("Authorization");if(!h)throw new Error("SIGN_IN_REQUIRED");const c=createClient(URL,ANON,{global:{headers:{Authorization:h}}});const {data,error}=await c.auth.getUser();if(error||!data.user)throw new Error("INVALID_SESSION");return data.user;}
async function sha(value:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("");}
function token(){return crypto.randomUUID().replaceAll("-","")+crypto.randomUUID().replaceAll("-","");}
async function gh(path:string,access:string,init:RequestInit={}){const r=await fetch("https://api.github.com"+path,{...init,headers:{"Authorization":`Bearer ${access}`,"Accept":"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28","Content-Type":"application/json",...(init.headers||{})}});const t=await r.text();let j:any={};try{j=t?JSON.parse(t):{}}catch{j={raw:t}}if(!r.ok)throw new Error(j?.message||`GitHub HTTP ${r.status}`);return j;}
async function connection(userId:string,workspaceId:string){const {data,error}=await admin.from("github_connections").select("*").eq("user_id",userId).eq("workspace_id",workspaceId).maybeSingle();if(error||!data)throw new Error("GITHUB_NOT_CONNECTED");return {...data,accessToken:await decryptSecret(data.access_token_ciphertext)};}
function safePath(p:string){const s=String(p||"").replaceAll("\\","/").replace(/^\/+/, "");if(!s||s.split("/").some(x=>x===".."||x==="."))throw new Error("Invalid repository path");return s;}
async function resolveWorkspace(userId:string,workspaceId:string,projectId:string){
  if(workspaceId)return workspaceId;
  if(projectId){const {data,error}=await admin.from("projects").select("workspace_id").eq("id",projectId).eq("owner_id",userId).maybeSingle();if(error)throw error;if(data?.workspace_id)return data.workspace_id;}
  throw new Error("WORKSPACE_REQUIRED");
}
async function start(user:any,workspaceId:string,projectId:string){workspaceId=await resolveWorkspace(user.id,workspaceId,projectId);if(!CLIENT_ID||!CLIENT_SECRET||!REDIRECT)throw new Error("GitHub OAuth is not configured");const state=token();const stateHash=await sha(state);const {error}=await admin.from("github_oauth_states").insert({state_hash:stateHash,user_id:user.id,workspace_id:workspaceId,expires_at:new Date(Date.now()+10*60*1000).toISOString()});if(error)throw error;const q=new URLSearchParams({client_id:CLIENT_ID,redirect_uri:REDIRECT,state,scope:"repo workflow read:user user:email"});return {url:`https://github.com/login/oauth/authorize?${q}`};}
async function callback(code:string,state:string){if(!CLIENT_ID||!CLIENT_SECRET||!REDIRECT)throw new Error("GitHub OAuth is not configured");const hash=await sha(state);const {data:s,error:se}=await admin.from("github_oauth_states").select("*").eq("state_hash",hash).maybeSingle();if(se||!s||new Date(s.expires_at).getTime()<Date.now())throw new Error("Invalid or expired OAuth state");await admin.from("github_oauth_states").delete().eq("state_hash",hash);const tr=await fetch("https://github.com/login/oauth/access_token",{method:"POST",headers:{"Accept":"application/json","Content-Type":"application/json"},body:JSON.stringify({client_id:CLIENT_ID,client_secret:CLIENT_SECRET,code,redirect_uri:REDIRECT})});const tj=await tr.json();if(!tr.ok||!tj.access_token)throw new Error(tj.error_description||"GitHub token exchange failed");const me=await gh("/user",tj.access_token);const cipher=await encryptSecret(tj.access_token);await admin.from("github_connections").upsert({user_id:s.user_id,workspace_id:s.workspace_id,github_user_id:String(me.id),github_login:me.login,access_token_ciphertext:cipher,scope:tj.scope||null,updated_at:new Date().toISOString()},{onConflict:"user_id,workspace_id"});return {redirect:`${ORIGIN}/?github=connected&workspace=${encodeURIComponent(s.workspace_id)}`};}
async function status(user:any,workspaceId:string){const {data,error}=await admin.from("github_connections").select("github_login,github_user_id,scope,updated_at").eq("user_id",user.id).eq("workspace_id",workspaceId).maybeSingle();if(error)throw error;return {connected:!!data,githubLogin:data?.github_login||null,githubUserId:data?.github_user_id||null,scope:data?.scope||null,updatedAt:data?.updated_at||null};}
async function repos(user:any,workspaceId:string){const c=await connection(user.id,workspaceId);const data=await gh("/user/repos?per_page=100&sort=updated",c.accessToken);const rows=data.map((r:any)=>({connection_id:c.id,workspace_id:workspaceId,owner_login:r.owner.login,repo_name:r.name,full_name:r.full_name,default_branch:r.default_branch||"main",private:!!r.private,html_url:r.html_url,metadata:{id:r.id}}));if(rows.length)await admin.from("github_repositories").upsert(rows,{onConflict:"connection_id,full_name"});return {repositories:rows};}
async function createRepo(user:any,workspaceId:string,body:any){const c=await connection(user.id,workspaceId);const name=safePath(body.name).split("/").pop()!;const r=await gh("/user/repos",c.accessToken,{method:"POST",body:JSON.stringify({name,description:String(body.description||"").slice(0,350),private:body.private!==false,auto_init:true})});await admin.from("github_repositories").upsert({connection_id:c.id,workspace_id:workspaceId,owner_login:r.owner.login,repo_name:r.name,full_name:r.full_name,default_branch:r.default_branch||"main",private:!!r.private,html_url:r.html_url,metadata:{id:r.id}},{onConflict:"connection_id,full_name"});return {repository:r};}
async function push(user:any,workspaceId:string,body:any){const c=await connection(user.id,workspaceId);const full=String(body.fullName||"");if(!/^[^/]+\/[^/]+$/.test(full))throw new Error("Invalid repository");const branch=String(body.branch||"main");const files=Array.isArray(body.files)?body.files.slice(0,500):[];if(!files.length)throw new Error("No files to push");const ref=await gh(`/repos/${full}/git/ref/heads/${encodeURIComponent(branch)}`,c.accessToken);const baseSha=ref.object.sha;const base=await gh(`/repos/${full}/git/commits/${baseSha}`,c.accessToken);const treeEntries=[];for(const file of files){const path=safePath(file.path);const content=String(file.content??"");const blob=await gh(`/repos/${full}/git/blobs`,c.accessToken,{method:"POST",body:JSON.stringify({content,encoding:"utf-8"})});treeEntries.push({path,mode:"100644",type:"blob",sha:blob.sha});}const tree=await gh(`/repos/${full}/git/trees`,c.accessToken,{method:"POST",body:JSON.stringify({base_tree:base.tree.sha,tree:treeEntries})});const commit=await gh(`/repos/${full}/git/commits`,c.accessToken,{method:"POST",body:JSON.stringify({message:String(body.message||"Update from ProjectX").slice(0,200),tree:tree.sha,parents:[baseSha]})});await gh(`/repos/${full}/git/refs/heads/${encodeURIComponent(branch)}`,c.accessToken,{method:"PATCH",body:JSON.stringify({sha:commit.sha,force:false})});return {commitSha:commit.sha,htmlUrl:`https://github.com/${full}/commit/${commit.sha}`};}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});try{const url=new URL(req.url);if(req.method==="GET" && url.searchParams.get("code") && url.searchParams.get("state")){return new Response("",{status:302,headers:{Location:(await callback(url.searchParams.get("code")!,url.searchParams.get("state")!)).redirect,...corsHeaders}});}const body=await req.json().catch(()=>({}));const action=String(body.action||"");if(action==="callback")return new Response("",{status:302,headers:{Location:(await callback(String(body.code||""),String(body.state||""))).redirect,...corsHeaders}});const u=await auth(req);let ws=String(body.workspaceId||"");if(action==="startOAuth"){return json({ok:true,...await start(u,ws,String(body.projectId||""))});}if(!ws)throw new Error("WORKSPACE_REQUIRED");if(action==="status")return json({ok:true,...await status(u,ws)});if(action==="listRepos")return json({ok:true,...await repos(u,ws)});if(action==="createRepo")return json({ok:true,...await createRepo(u,ws,body)});if(action==="pushFiles")return json({ok:true,...await push(u,ws,body)});if(action==="disconnect"){await admin.from("github_connections").delete().eq("user_id",u.id).eq("workspace_id",ws);return json({ok:true});}throw new Error("Unknown action");}catch(e){return json({ok:false,error:e instanceof Error?e.message:String(e)},400);}});