import { createClient } from "npm:@supabase/supabase-js@2";
import { corsHeaders, json } from "../_shared/cors.ts";
import { createHash } from "node:crypto";
import * as XLSX from "npm:xlsx@0.18.5";
import mammoth from "npm:mammoth@1.8.0";
import pdfParse from "npm:pdf-parse@1.1.1";
const URL=Deno.env.get("SUPABASE_URL")!;
const ANON=Deno.env.get("SUPABASE_ANON_KEY")||Deno.env.get("SUPABASE_PUBLISHABLE_KEY")!;
const SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||Deno.env.get("SUPABASE_SECRET_KEY")!;
const admin=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
const MAX=5*1024*1024;
async function auth(req:Request){const h=req.headers.get("Authorization");if(!h)throw new Error("SIGN_IN_REQUIRED");const c=createClient(URL,ANON,{global:{headers:{Authorization:h}}});const {data,error}=await c.auth.getUser();if(error||!data.user)throw new Error("INVALID_SESSION");return data.user;}
function bytes(b64:string){const s=String(b64||"");if(s.length>Math.ceil(MAX*4/3)+100)throw new Error("FILE_TOO_LARGE");const bin=atob(s.includes(",")?s.split(",").pop()!:s);if(bin.length>MAX)throw new Error("FILE_TOO_LARGE");return Uint8Array.from(bin,c=>c.charCodeAt(0));}
function textFromBytes(b:Uint8Array){return new TextDecoder().decode(b);}
async function extract(name:string,mime:string,b:Uint8Array){const lower=name.toLowerCase();if(mime.startsWith("text/")||/\.(txt|md|markdown|json|csv|xml|html|css|js|ts|tsx|jsx|sql|yaml|yml|toml|env)$/i.test(lower))return textFromBytes(b).slice(0,200000);if(/\.pdf$/i.test(lower)||mime==="application/pdf"){const r=await pdfParse(Buffer.from(b));return String(r.text||"").slice(0,200000);}if(/\.docx$/i.test(lower)||mime==="application/vnd.openxmlformats-officedocument.wordprocessingml.document"){const r=await mammoth.extractRawText({buffer:Buffer.from(b)});return String(r.value||"").slice(0,200000);}if(/\.(xlsx|xls)$/i.test(lower)||/spreadsheetml|ms-excel/.test(mime)){const wb=XLSX.read(b,{type:"array"});return wb.SheetNames.map((n:string)=>`# ${n}\n${XLSX.utils.sheet_to_csv(wb.Sheets[n])}`).join("\n\n").slice(0,200000);}return ""; }
async function access(userId:string,projectId:string){const {data:p}=await admin.from("projects").select("id,workspace_id").eq("id",projectId).maybeSingle();if(!p)throw new Error("PROJECT_NOT_FOUND");const {data:m}=await admin.from("workspace_members").select("role").eq("workspace_id",p.workspace_id).eq("user_id",userId).maybeSingle();if(!m||!["owner","admin","editor"].includes(m.role))throw new Error("FORBIDDEN");return p;}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});try{const u=await auth(req);const b=await req.json().catch(()=>({}));const p=await access(u.id,String(b.projectId||""));const data=bytes(String(b.dataBase64||""));const name=String(b.fileName||"upload.bin").slice(0,180);const mime=String(b.mimeType||"application/octet-stream").slice(0,120);const hash=createHash("sha256").update(data).digest("hex");const bucket=String(Deno.env.get("PROJECTX_RESOURCE_BUCKET")||"builder-attachments");const path=`${p.id}/resources/${crypto.randomUUID()}-${name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;const up=await admin.storage.from(bucket).upload(path,data,{contentType:mime,upsert:false});if(up.error)throw up.error;const resource={project_id:p.id,user_id:u.id,storage_bucket:bucket,storage_path:path,original_name:name,mime_type:mime,size_bytes:data.length,sha256:hash,extraction_status:"processing",metadata:{}};const {data:row,error}=await admin.from("project_resources").insert(resource).select().single();if(error)throw error;try{const extracted=await extract(name,mime,data);const {data:ready,error:e}=await admin.from("project_resources").update({extracted_text:extracted,extraction_status:"ready",metadata:{extractedCharacters:extracted.length} ,updated_at:new Date().toISOString()}).eq("id",row.id).select().single();if(e)throw e;return json({ok:true,resource:ready});}catch(e){await admin.from("project_resources").update({extraction_status:"failed",error:e instanceof Error?e.message:String(e),updated_at:new Date().toISOString()}).eq("id",row.id);return json({ok:true,resource:{...row,extraction_status:"failed",error:e instanceof Error?e.message:String(e)}});} }catch(e){return json({ok:false,error:e instanceof Error?e.message:String(e)},400);}});